### ISSUE TITLE
Uncaught exception? 

### ISSUE THREAD

**Issue by BKeyport** [Tom-Hirschberger/MMM-CommandToNotification#5]
```
0|MagicMirror  | [24.05.2023 13:42.53.777] [LOG]   MMM-CommandToNotification: Calling commands
0|MagicMirror  | [24.05.2023 13:42.53.779] [LOG]   Running /usr/bin/curl asynchronous
0|MagicMirror  | [24.05.2023 13:42.53.814] [LOG]   Running ~/MagicMirror/modules/MMM-CommandToNotification/scripts/temperature/bme280 asynchronous
0|MagicMirror  | [24.05.2023 13:42.53.849] [LOG]   Running ~/MagicMirror/modules/MMM-CommandToNotification/scripts/temperature/htu21 asynchronous
0|MagicMirror  | [24.05.2023 13:42.53.896] [ERROR] Whoops! There was an uncaught exception...
0|MagicMirror  | [24.05.2023 13:42.53.905] [ERROR] TypeError: Cannot read properties of null (reading 'trim')
0|MagicMirror  |     at ChildProcess.<anonymous> (/home/bkey1970/MagicMirror/modules/MMM-CommandToNotification/node_helper.js:56:86)
0|MagicMirror  |     at ChildProcess.emit (node:events:513:28)
0|MagicMirror  |     at maybeClose (node:internal/child_process:1093:16)
0|MagicMirror  |     at Socket.<anonymous> (node:internal/child_process:451:11)
0|MagicMirror  |     at Socket.emit (node:events:513:28)
0|MagicMirror  |     at Pipe.<anonymous> (node:net:757:14)
0|MagicMirror  | [24.05.2023 13:42.53.905] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|MagicMirror  | [24.05.2023 13:42.53.905] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|MagicMirror  | [24.05.2023 13:42.54.004] [LOG]   curCmdConfig: {"script":"~/MagicMirror/modules/MMM-CommandToNotification/scripts/temperature/bme280","args":"0x77","timeout":5000,"sync":false,"notifications":["TempRoom"]}
0|MagicMirror  | [24.05.2023 13:42.54.272] [INFO]  Calendar-Fetcher: Broadcasting 72 events.
0|MagicMirror  | [24.05.2023 13:42.54.658] [LOG]   curCmdConfig: {"script":"~/MagicMirror/modules/MMM-CommandToNotification/scripts/temperature/htu21","timeout":5000,"sync":false,"notifications":["TempCase"]}
```

keep getting this randomly. is there anything that can be done? When this happens, all notifications turn to NA.

**Comment by Tom-Hirschberger** [comment]
Hi,

i think a catch of the exception is not a problem. At least all other scripts should keep running and return a valid result then.
It looks like the script you call exits without returning any output which causes the problem.

**Comment by Tom-Hirschberger** [comment]
Just released version 0.0.5 of the module which should fix the issue.

**Comment by BKeyport** [comment]
Indeed, it's no longer reporting that error - I think what's happening is that my weatherlink station is reporting back a null when it happens to be chewing on data from the devices on the roof - the control module is running on an ESP8266 after all. 

What I don't understand is why other scripts (BME280 and HTU21) are also blanking to N/A value. Would it be a possible upgrade to hold previous values if not replaced for the notification - and just log at INFO level that a script reported back null? 

Also, I'd put the "curCmdConfig" log item in DEBUG. No reason to have it in the base log...

**Comment by Tom-Hirschberger** [comment]
I think the problem was that the modules node_helper cancelled the whole reschedule function in the moment the exception occurred and no other sensors had been processed.
Thats why all sensor got to NA at that moment.

You use MMM-ValuesByNotification to display the values of the notifications, right?
This module already has a reuse feature integrated. With the config option `reuseCount` you can control how often a value should be reused before the `naValue` is used.
I decided to add the logic to the module which displays the values instead of the module who produces them.

You are right. `curCmdConfig` should be debug. I do not use the MagicMirror logger at the moment but simply print to the console. I added a debug flag to suppress some messages for the moment. Maybe i change to the Logger with the next release.

**Comment by BKeyport** [comment]
I do believe the issue is fixed as it could be. Closing as a result. Thanks.
