### ISSUE TITLE
scripts dependencies not resolved

### ISSUE THREAD

**Issue by sdetweil** [Tom-Hirschberger/MMM-CommandToNotification#8]
user trying to use a script, but it has dependencies that were never installed, or documented to be needed...

**Comment by Tom-Hirschberger** [comment]
Hi Sam, do not exactly now what you mean.

The module itself only uses only dependencies of node.

If a user wants to call a script he needs to take care about the dependencies by him self.
If a error occurs the return code or the output contains a pattern the module can send different notifications.

**Comment by Tom-Hirschberger** [comment]
Found the thread in the forum.

Will add a Readme containing instructions of how to install the deps.

Currently only a comment is in the script itself.

**Comment by sdetweil** [comment]
right. the user tries to use the script  but it will fail  if the python libs or system dep not installed

**Comment by Tom-Hirschberger** [comment]
Done. I added some more documentation to the reame of the example scripts

**Comment by sdetweil** [comment]
you could tell if the path is absolute, (starts w /)

and not depend on the user for this

**Comment by Tom-Hirschberger** [comment]
Hi,

sorry but i am again not sure what you mean exactly.
There are three scenarios which can happen:
* the user wants to call a script by its relative path
* the user wants to call a script by its absolute path
* the user wants to call a script which is in the system `PATH`

if the user wants to call a script by its relative path the path will look something like:
* ../../../myscript.bash
* temperature/bme280
* ./randomInteger.js

if the user want to use a script which is part of the `PATH` there will be no starting `./` or `/`.

I could add a check if the command does not start with a `/` but it contains a `/` it is a relative path.
But if the user wants to call a script which is in the `scripts` directory (which is my working directory for the script calls) and calls it with lets say `randomInteger.js` i do not know if it is a script in the `PATH` or in the `scripts` directory.

**Comment by sdetweil** [comment]
0k. your doc  said absolute or relative 

![Screenshot_20240427_122714_Chrome](https://github.com/Tom-Hirschberger/MMM-CommandToNotification/assets/1498142/a0c7dad9-4e51-4766-b73f-f7866658e264)



absolute to me means from the root
/home/pi/...   

relative is anything else

so scripts/dht22.py
is relative 

doesn't need the ./ you can do that.   
if it starts w a dot, then don't add ./

just  my opinion.. users don't read, don't know file systems..  

just trying  to reduce trouble reports and user frustration  w things not working 

you can also build that path and test it, and report if not found...before trying to execute it

**Comment by Tom-Hirschberger** [comment]
Your right. That's definitely a point.
I think i can add this easily.

Will do this as fast as I can.

**Comment by Tom-Hirschberger** [comment]
Hi Sam,

just released version 0.0.7 of the module which includes your suggestions of path and permissions checks.
It is possible to run scripts either with or without the `./` now.

Needed to take care about a rare edge case if a user wants to call lets say `randomNumber.js` and puts it in his $PATH to call it. I first check if the script is in the `scripts` directory now and expect it to be in $PATH it is not there, now.

**Comment by sdetweil** [comment]
cool. nice work
